### ISSUE TITLE
Upgrade unit tests

### ISSUE THREAD

**Issue by ssebro** [agco/harvesterjs#102]
This ticket is to port the unit test style from acgo's iam repo to harvester.

The unit tests on harvester are lagging behind the best practices employed on agco's internal apis, and we'd like to bring those best practices to harvester.

Here's why we're doing this:
- Tests on harvester depend on each other. We'd rather have tests be able to stand on their own.
- The basic test style is cumbersome and way too complex for what it delivers.
- By using .js files that return json to power our fixtures (rather than plain old .json files), our fixtures can contain comments that let developers know about interlinking dependency issues.
- We want the same testing style applied across all our apps in general to reduce switching costs and mental overhead.

Here's what you'll have to do:
- Grab a copy of iam. A recent build is on heroku on the master branch of the app agco-iam-predev.
- Read through the unit tests of harvester. For now I want you to focus on the tests in limits.js. Your intermediate unit tests will probably skip over or not include any of the other tests for now - we'll have you pull them in later, but it's always easier to start with more attainable goal posts. Note that the tests are being run by the all.js file, which is being run by mocha, which is being kicked off by the runner.js file. This complexity is a part of what you'll help us move away from.
- Be aware that we use git flow to manage our git branching strategy, with the default names for all branches. This means that when you grab harvester, you'll have to install git flow, pull all remote branches, and do ```git flow init``` on the repo before you start the new ticket with ```git flow feature start {harvester issue number}```. If you haven't used git flow before, please check out the excellent documentation / cheat sheet at http://danielkummer.github.io/git-flow-cheatsheet/
- Read through the unit tests of iam. There are only a few, so feel free to read them all. Note how the tests are launched by the simple test script in package.json - that's the sort of test strategy we want to promote. I'd imagine that your test script in package.json for the new harvester tests should look near identical to that of iam.
- Finally, contribute ideas. Let us know where we could be doing things better. We know you have a lot to add and we want to learn glean as much as we can from your insights. I know you love testing - definitely let us know how we could do better.

- After you're done with limits.js, check in with me so we can chat about the direction, but if I'm busy or working at a different time from you, feel free to move on to the other test files - don't let me block your thread!

**Comment by blabno** [comment]
Resolved in b9f95c0784014828bbb89e8cf3042deb36ee42e5
