### ISSUE TITLE
remove neDb adapter

### ISSUE THREAD

**Issue by kristofsajdak** [agco/harvesterjs#15]
neDb adapter is not maintained at this point. Several features are broken/missing

Perhaps at some point we might re-introduce support for multiple databases,
however right now we only support Mongodb as the persistence mechanism.

**Comment by jaydson** [comment]
As neDb adapter support was already removed, we can close this issue, right?

**Comment by kristofsajdak** [comment]
Done, there is probably a couple other issues which have gone stale or have already been executed. Will have a chat with some of the other team members to clean this up

**Comment by jaydson** [comment]
:+1:
