### ISSUE TITLE
scary PATCH injection

### ISSUE THREAD

**Issue by superpeixeboi** [agco/harvesterjs#203]
PATCH http://app.com/model/:id
[
   { "path": "///$unset", "value": { "fieldName": "" }, "op": "replace" }
]

This is actually allowed... I believe this was not supposed to be used this way.

**Comment by waldemarnt** [comment]
Thank you for the point.
We decided to remove PATCH on https://github.com/agco/harvesterjs/pull/206 while we design its functionality to add again.

To ensure that old client will not break we generated a new Major tag https://github.com/agco/harvesterjs/tree/3.0.0

Cheers
