### ISSUE TITLE
Change internal Promise lib from RSVP to Bluebird

### ISSUE THREAD

**Issue by kristofsajdak** [agco/harvesterjs#40]
Bluebird has a number of advantages of RSVP
- ability to produce [long stacktraces](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiselongstacktraces---void), this works with [longjohn](https://github.com/mattinsler/longjohn). a must-have really to do any kind of decent debugging with promises
- supports [Promisification](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification)
- has a bunch of nice [Collection methods](https://github.com/petkaantonov/bluebird/blob/master/API.md#collections) which we could leverage
- ...

Easy to implement, current codebase uses A+ methods only. 
Perhaps the downstream consumers of the adapter or transform functions might be impacted though, needs a bit of investigation.

**Comment by mavdi** [comment]
done.
