### ISSUE TITLE
Wrong documentation page

### ISSUE THREAD

**Issue by jaydson** [agco/harvesterjs#80]
The README file says: 
> Documentation : http://agco.github.io/harvesterjs

But there's no documentation at all on that page.

**Comment by kristofsajdak** [comment]
Thanks for reviewing this.

I am aware the docs are a bit sparse currently, it is our intention to get this into shape over the coming months.

**Comment by jaydson** [comment]
Got it.
Perhaps change the README file for something like this should be more helpful:
> Documentation: Soon

**Comment by kristofsajdak** [comment]
Point taken :-) removed the link from the README for now, and replaced it with an IOU note

**Comment by jaydson** [comment]
cool :)
