### ISSUE TITLE
Simple example doesn't work

### ISSUE THREAD

**Issue by jaydson** [agco/harvesterjs#82]
I'm trying to run a simple example, but it's not working as expected.
The error: 
```json
{
  "errors": [
    {
      "status": 500,
      "detail": "TypeError: Cannot read property 'forEach' of undefined",
      "href": "about:blank",
      "title": "Oops, something went wrong."
    }
  ]
}
```

My sample application looks like this:  
```javascript
var harvester = require('harvesterjs');
var app = harvester({
	db: 'mydatabase'
});

app.resource('artist', {
	name: String
})
.listen(1337);
```

A simple GET works fine:
```
GET /artists HTTP/1.1
Host: localhost:1337
```
returns:
```json
{
  "artists": []
}
```
When a try to POST:
```
POST /artists HTTP/1.1
Host: localhost:1337
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "artist",
    "attributes": {
      "name": "Sepultura"
    }
  }
}
```
I get the error mentioned above.

What I'm missing here?

**Comment by kristofsajdak** [comment]
The jsonapi spec has undergone some changes since Harvesterjs was implemented
We are kind of waiting until 1.0 is finalised (21st of May) before we start changing stuff around

I added jsonapi 1.0 compliance to the roadmap, we need to plan with the team when we can make the change though. I will update the docs as soon as we have a date for this

It's a bit late here so I didn't have time to test, but your request should look like this :

```` 
POST /artists HTTP/1.1
Host: localhost:1337
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "artists": [{
      "name": "Sepultura"
  }]
}
````

**Comment by kristofsajdak** [comment]
You need some changes to your config as well, we don't support the in-memory neDb or any other databases, only Mongodb. 

We made this choice after running into subtle differences using queries against both databases, at this point in time we need to make one thing work really well rather than having broad support for multiple databases.

There are also specific Mongodb features (oplog) which we use to power SSE, which is a huge benefit for us

Let me see if I can craft an example app with a dockerized Mongodb setup, that way it's easy for people to pick up and start playing with.

It's probably tomorrow at earliest though, it's getting kind of late here

**Comment by jaydson** [comment]
Thanks @kristofsajdak.
This example app will help me (and others) a lot.

Just to let you know, i tried the format data you showed, but it also didn't work.
About the config, I'm using mongodb, and i saw the database is being created, the problem is when I try to store some data.

**Comment by kristofsajdak** [comment]
@jaydson I have PR out with a new working example, including instructions on how to set this up
https://github.com/agco/harvesterjs/pull/83

@dclucas is still reviewing, but you can already have a look and start playing with it
Let me know what you think

**Comment by jaydson** [comment]
Hi @kristofsajdak, thanks for this.

I kept the example simpler, as i'm not using Docker (Linux 32 bits here) and i don't want the streams feature by now.
```javascript
var harvester = require('harvesterjs');
var app = harvester({
	adapter: 'mongodb',
	connectionString: "localhost:27017/mydatabase"
});

app.resource('artists', {
	name: String
})
.listen(1337);
```
It still failing.
I saw you're passing a `json` property name on the payload:
```javascript
 $http.post(apiHost + '/artists', {json: sepultura})
```
What is the point of such property? It is required?
The payload will looks like this:
```
{
    "json": {
        "artists": [{
            "name": "Sepultura"
        }]
    }
}
```
I tried a lot of json payload formats, and none of them worked.
I don't know, maybe I'm missing something on the configuration, or there's something wrong in my current environment, but there's no way i can get Harvester working.

Let's see if @dclucas can help us.

Thanks!

**Comment by dclucas** [comment]
Just merged the PR with the example. I'm now firing an example based on your code...

**Comment by jaydson** [comment]
:+1:

**Comment by dclucas** [comment]
So, using a local REST tool I was able to post an artist by using the following payload:
```
{
  "artists": [ { "name": "Sepultura" }]
}
```

Using application/json (that's what I can get from POSTMAN) as the content-type. I'll try curling next and post my results...

**Comment by dclucas** [comment]
Curl'ing works like a charm too. Which content-type are you using on these calls?
```
curl -XPOST -H "Content-type: application/json" -d '{
  "artists": [ { "name": "Sepultura" }]
}' 'http://localhost:1337/artists'
```

**Comment by dclucas** [comment]
And, to be absolutely safe, can you GET from the API? What happens if you add a record by hand in mongo and then GET?

Right now, the safest bet seems to be on payload format or on environment. One way or another, this is quite probably an error handling bug, at the very least...

**Comment by jaydson** [comment]
I found the issue.
I was following the JSONAPI spec, and in the ["Creating Resources"](http://jsonapi.org/format/#crud-creating) section there's this example:
```
POST /photos
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
```
I was always sending those headers.  
Testing with your CURL example, it works like a charm indeed.
I've just removed the headers from my requests and it also works in the browser and in Postman.

Thing is, the error Harvester is showing passing wrong headers is not very helpful: `Oops, something went wrong`.  
Maybe there's some exception not covered (in Fortune).

Thank you so much for your help guys.  
Now I can keep hacking.

**Comment by jaydson** [comment]
I'll file a issue for that header exception.

**Comment by dclucas** [comment]
Great, tks for the heads-up.

**Comment by jaydson** [comment]
https://github.com/agco/harvesterjs/issues/84

**Comment by kristofsajdak** [comment]
Glad to hear you guys sorted it out

@jaydson  if you are still curious, the json property in the code below is an [option for the request library](https://github.com/request/request#requestoptions-callback), which is wrapped by the http-as-promised library used in the example.

````javascript
 $http.post(apiHost + '/artists', {json: sepultura})
````

The json option instructs the 'request' lib to stringify the object and auto-sets the 'application/json' content-type header on the request

**Comment by jaydson** [comment]
@kristofsajdak got it.
