### ISSUE TITLE
Upstream has updated to a new major version

### ISSUE THREAD

**Issue by daliwali** [agco/harvesterjs#90]
Hey guys,

Just want to let you know that upstream has a new release that greatly simplifies adapters, and implements multiple serializers (including JSON API 1.0). It would be nice to investigate if the features in this fork can be merged into `fortune-mongodb` somehow.

**Comment by kristofsajdak** [comment]
Absolutely, you have given us a great head start so we would be more than happy to contribute back. I'll have a chat with the team and see who we can assign to this. 

Congratulations on the new release btw, will have a more in-depth look a bit later today, but looks very interesting. 

What made you go with your own format, rather than jsonapi ?

**Comment by daliwali** [comment]
Awesome. from what I see, most of the work that is done in this fork is extending the MongoDB adapter. The one I wrote for the new major version just implements the minimum requirements of the Adapter interface. I'm planning on writing a PostgreSQL adapter that implements something MongoDB can't, transactions. After this has been proven, along with more complete adapters with unique features, then I think 1.0 will be ready. Your help with the MongoDB adapter would be greatly appreciated :)

Three reasons why JSON API is now just another component:

- I wanted to completely decouple the serialization format from Fortune.
- The library can work using a default serializer that uses Fortune's internal format.
- The specification after hitting 1.0 has plenty of rough edges and [isn't really REST](http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven), the big problems being that it has no entry point and that it is tightly coupled with HTTP (the spec defines status codes, http verbs, http headers, query strings).

**Comment by ssebro** [comment]
Were there any features that you've taken a look at on harvester that you're particularly interested in having on fortune? We could probably campaign for a limited amount of time to be spent on back-porting if you could help us isolate the most impactful items.

**Comment by daliwali** [comment]
There are a few specifics that would be nice to implement:

- Update operators (they should already work, just need to write logic to apply them to preview updates)
- Flags for indexed fields / unique fields / required (non-nullable) fields

What's done in 1.0-alpha and why you should consider migrating:

- JSON API 1.0 compliance
- Inverse links, [well-tested implementation](https://github.com/fortunejs/fortune/blob/master/test/integration/methods/update.js).
- Dispatcher emits "change" events, independently of DB implementation (triggers in RDBMS, etc).

**Comment by ssebro** [comment]
Though json API 1.0 compliance is alluring, we're actually heads-down on a new release of harvester, so now's not quite the right time for us to be considering migrating.
